flyway.url=jdbc:postgresql://localhost:5432/taradome
flyway.user=taradome_admin
flyway.password=CHANGE_ME
flyway.locations=filesystem:./sql
flyway.baselineOnMigrate=true
flyway.validateMigrationNaming=true
